# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bytedance_growth_rta.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x62ytedance_growth_rta.proto\x12\x14\x62ytedance_growth_rta\"V\n\x08\x43\x61idInfo\x12\r\n\x05\x63\x61id1\x18\x01 \x01(\t\x12\x15\n\rcaid_version1\x18\x02 \x01(\t\x12\r\n\x05\x63\x61id2\x18\x03 \x01(\t\x12\x15\n\rcaid_version2\x18\x04 \x01(\t\"\xb5\x01\n\nDeviceInfo\x12\x14\n\x0c\x64\x65vice_model\x18\x01 \x01(\t\x12\x0c\n\x04oaid\x18\x02 \x01(\t\x12\x10\n\x08oaid_md5\x18\x03 \x01(\t\x12\x0c\n\x04imei\x18\x04 \x01(\t\x12\x10\n\x08imei_md5\x18\x05 \x01(\t\x12\x0c\n\x04idfa\x18\x06 \x01(\t\x12\x10\n\x08idfa_md5\x18\x07 \x01(\t\x12\x31\n\tcaid_info\x18\x08 \x01(\x0b\x32\x1e.bytedance_growth_rta.CaidInfo\"\x8f\x02\n\x07Request\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x12\n\nrta_tokens\x18\x03 \x03(\t\x12\x35\n\x0b\x64\x65vice_info\x18\x04 \x01(\x0b\x32 .bytedance_growth_rta.DeviceInfo\x12\x0b\n\x03rit\x18\x05 \x01(\t\x12\n\n\x02ip\x18\x06 \x01(\t\x12\n\n\x02ua\x18\x07 \x01(\t\x12@\n\nuser_label\x18\x08 \x03(\x0b\x32,.bytedance_growth_rta.Request.UserLabelEntry\x1a\x30\n\x0eUserLabelEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\">\n\tRtaResult\x12\x0e\n\x06is_bid\x18\x01 \x01(\x08\x12\x13\n\x0bprice_score\x18\x02 \x01(\x01\x12\x0c\n\x04vids\x18\x03 \x03(\x03\"\xc5\x01\n\x08Response\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x43\n\x0brta_results\x18\x03 \x03(\x0b\x32..bytedance_growth_rta.Response.RtaResultsEntry\x1aR\n\x0fRtaResultsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12.\n\x05value\x18\x02 \x01(\x0b\x32\x1f.bytedance_growth_rta.RtaResult:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bytedance_growth_rta_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST_USERLABELENTRY']._loaded_options = None
  _globals['_REQUEST_USERLABELENTRY']._serialized_options = b'8\001'
  _globals['_RESPONSE_RTARESULTSENTRY']._loaded_options = None
  _globals['_RESPONSE_RTARESULTSENTRY']._serialized_options = b'8\001'
  _globals['_CAIDINFO']._serialized_start=52
  _globals['_CAIDINFO']._serialized_end=138
  _globals['_DEVICEINFO']._serialized_start=141
  _globals['_DEVICEINFO']._serialized_end=322
  _globals['_REQUEST']._serialized_start=325
  _globals['_REQUEST']._serialized_end=596
  _globals['_REQUEST_USERLABELENTRY']._serialized_start=548
  _globals['_REQUEST_USERLABELENTRY']._serialized_end=596
  _globals['_RTARESULT']._serialized_start=598
  _globals['_RTARESULT']._serialized_end=660
  _globals['_RESPONSE']._serialized_start=663
  _globals['_RESPONSE']._serialized_end=860
  _globals['_RESPONSE_RTARESULTSENTRY']._serialized_start=778
  _globals['_RESPONSE_RTARESULTSENTRY']._serialized_end=860
# @@protoc_insertion_point(module_scope)
